# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_auto_20170317_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='image_paths',
        ),
        migrations.AddField(
            model_name='meeting',
            name='main_image',
            field=models.ImageField(default='/Users/jihun/Projects/LinkU/linku_backend/media/meeting_default_image.jpg', upload_to=''),
        ),
    ]
